__title__ = 'syllapy'
__version__ = '0.1'
__summary__ = 'Calculate syllables for English language words.'
__uri__ = 'https://github.com/mholtzscher/syllapy'
__author__ = 'Michael Holtzscher'
__email__ = 'mholtz@protonmail.com'
__license__ = 'MIT'
